import "./globals.css";
import "./all.min.css";
import { Inter, Poppins } from "next/font/google";
import Header from "@/components/Header";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins",
  weight: ["400", "500", "600", "700"],
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} w-full flex flex-row justify-start`}
      >
        <div className="lg:w-[174px] xl:w-[218px] 2xl:w-[273px] bg-ash-500 min-h-screen"></div>
        <div className="w-full lg:w-[83%] 2xl:w-[85.5%] flex flex-col justify-start items-start">
          <Header />
          <div className="w-full flex flex-col justify-start">{children}</div>
        </div>
      </body>
    </html>
  );
}

